declare module "lucide-react" {
  import type { FC, SVGProps } from "react"
  type IconProps = SVGProps<SVGSVGElement> & { size?: number }
  type Icon = FC<IconProps>
  export const ArrowUp: Icon
  export const Award: Icon
  export const Bell: Icon
  export const Bookmark: Icon
  export const BookOpen: Icon
  export const Calendar: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const Clock: Icon
  export const Download: Icon
  export const Facebook: Icon
  export const FileText: Icon
  export const Filter: Icon
  export const Globe: Icon
  export const Headphones: Icon
  export const Heart: Icon
  export const HelpCircle: Icon
  export const Home: Icon
  export const Instagram: Icon
  export const Loader2: Icon
  export const Lock: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const MapPin: Icon
  export const Menu: Icon
  export const Minus: Icon
  export const Phone: Icon
  export const Play: Icon
  export const Plus: Icon
  export const Search: Icon
  export const Send: Icon
  export const Settings: Icon
  export const ShoppingBag: Icon
  export const ShoppingCart: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Trash2: Icon
  export const User: Icon
  export const Users: Icon
  export const Video: Icon
  export const X: Icon
  export const Package: Icon
  export const Boxes: Icon
  export const Layers: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const CheckCircle2: Icon
  export const XCircle: Icon
  export const AlertTriangle: Icon
  export const RefreshCw: Icon
  export const RotateCw: Icon
  export const Edit2: Icon
  export const ExternalLink: Icon
  export const Tag: Icon
  export const LayoutDashboard: Icon
  export const GraduationCap: Icon
  export const ArrowRight: Icon
  export const ArrowLeft: Icon
  export const TrendingUp: Icon
  export const ArrowUpDown: Icon
  export const CheckCircleBig: Icon
  export const BarChart3: Icon
  export const MessageSquare: Icon
  export const Megaphone: Icon
  export const Folder: Icon
  export const Key: Icon
  export const Eye: Icon
  export const FileSpreadsheet: Icon
  export const Copy: Icon
  export const Image: Icon
  export const History: Icon
  export const Sliders: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const Upload: Icon
  export const DollarSign: Icon
  export const Activity: Icon
}
